config/routes.rb
RottenMangoes::Application.routes.draw do

  get 'search', to: 'movies#search'

  namespace :admin do
    resources :users
  end

  # get 'reviews/new'

  # get 'reviews/create'

  # get 'sessions/new'

  # get 'sessions/create'

  resources :movies

  resources :users, only: [:new, :create]

  # resources :sessions, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  root to: 'movies#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # it adds virtual attributes password
  # and password_confirmation to our user model.
  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  has_many :reviews

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_admin_access

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "User was successfully created, #{@user.firstname}!"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy

    # Mailers are really just another way to render a view.
    # Instead of rendering a view and sending out the HTTP protocol,
    # they are just sending it out through the email protocols instead.
    # Due to this, it makes sense to just have your controller tell the Mailer
    # to send an email when a user is successfully created.

    # Mailer --
    # app/mailers/user_mailer.rb

    # just edit the app/controllers/admin/users_controller.rb
    # make it instruct the UserMailer to deliver an email to the user being deletedd
    # by an Admin
    # by editing the destroy action
    # and inserting a call to UserMailer.welcome_email
    # right before the user is successfully deleted.


    @user = User.find(params[:id])

    # Tell the UserMailer to send a welcome email after desroy
    temp = UserMailer.account_deleted_notice_email(@user)

    temp.deliver

    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin edit User</h1>

<%= form_for( @user, url: admin_user_path) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/index.html.erb
    <h1>Admin Users</h1>
    <%= link_to "Create a user", new_admin_user_path %>
    <hr>
    <% @users.each do |user| %>
      <h4>Email: <%= user.email %> </h4>
      <h4>Full Name: <%= user.full_name %></h4>
      <h4>Go to User details: <%= link_to user.full_name, admin_user_path(user) %>
      <hr>
    <% end %>

app/views/admin/users/new.html.erb
<h1>Admin add new User</h1>

<%= form_for( @user, url: admin_users_path) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
    <h1>Admin User Details</h1>
    <!-- <%= link_to "Edit a user", edit_admin_user_path %> -->

     <h2><%= @user.lastname %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>)</h2>
    <hr>

    <h4>Email: <%= @user.email %> </h4>
    <h4>Full Name: <%= @user.full_name %></h4>
    <hr>