config/routes.rb
RottenMangoes::Application.routes.draw do

  get 'search', to: 'movies#search'

  namespace :admin do
    resources :users
  end

  # get 'reviews/new'

  # get 'reviews/create'

  # get 'sessions/new'

  # get 'sessions/create'

  resources :movies

  resources :users, only: [:new, :create]

  # resources :sessions, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  root to: 'movies#index'
end

app/views/layouts/_footer.html.erb
<footer>
  <small>


    <!-- create conditional "log in," "sign up," and "log out" links in the page footer.
    If a user isn't logged in, they should see the "log in" and "sign up" links.
    If they are, they should see that they're logged in and a "log out" link.
    -->

    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
          <% if session[:admin] %>
            <p>Signed in as Admin User (<%= link_to "Admin Home Page", admin_users_path %>)<p>
          <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>